version: "3.9"
services:
  api:
    image: erikrios/go-ca:1.0
    restart: always
    container_name: go-deployment
    ports: 
      - '8080:8080'
    expose:
      - '8080'
  db:
    image: mysql/mysql-server:5.7
    restart: always
    container_name: dev-db-mysql
    environment:
      MYSQL_DATABASE: 'library'
      MYSQL_ROOT_PASSWORD: 'erikrios'
    ports:
      - '3306:3306'
    expose:
      - '3306'
