// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	entities "github.com/erikrios/go-clean-arhictecture/entities"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: users
func (_m *UserRepository) FindAll(users *[]entities.User) error {
	ret := _m.Called(users)

	var r0 error
	if rf, ok := ret.Get(0).(func(*[]entities.User) error); ok {
		r0 = rf(users)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: user
func (_m *UserRepository) Insert(user *entities.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: user
func (_m *UserRepository) Login(user *entities.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
